"""
Capa de acceso a datos de la base de datos (CRUD).

Facade: re-exporta todo desde src.core.repositories para que los imports
existentes sigan funcionando:

  from src.core import db_repository as repo
  from src.core.db_repository import get_administraciones, create_comunidad, ...
"""

from src.core.repositories import (
    FUZZY_MATCH_THRESHOLD,
    HISTORIAL_DEFAULT_LIMIT,
    get_administracion_por_id,
    get_administraciones,
    get_administraciones_para_tabla,
    buscar_administracion_por_nombre,
    buscar_administracion_por_email,
    buscar_administraciones_fuzzy,
    create_administracion,
    update_administracion,
    delete_administracion,
    get_comunidad_por_id,
    get_comunidades,
    get_comunidades_para_tabla,
    buscar_comunidad_por_nombre,
    buscar_comunidades_fuzzy,
    create_comunidad,
    update_comunidad,
    delete_comunidad,
    get_contactos,
    get_contactos_para_tabla,
    get_contactos_por_administracion_id,
    get_contactos_por_comunidad_id,
    get_administracion_ids_para_contacto,
    get_comunidad_ids_para_contacto,
    set_administracion_contacto,
    set_comunidad_contacto,
    set_contactos_para_administracion,
    set_contactos_para_comunidad,
    create_contacto,
    update_contacto,
    delete_contacto,
    registrar_presupuesto,
    get_historial_reciente,
    actualizar_acceso,
    actualizar_total,
    eliminar_historial,
    buscar_historial,
    get_presupuesto_por_ruta,
    get_presupuesto_detalle_por_ruta,
    get_presupuestos_por_estado,
    upsert_presupuesto,
    upsert_presupuesto_finalizado,
    get_partidas_de_presupuesto,
    get_presupuestos_para_tabla,
    actualizar_estado_presupuesto,
    limpiar_presupuestos_huerfanos,
    get_all_presupuestos_cache,
)

__all__ = [
    "FUZZY_MATCH_THRESHOLD",
    "HISTORIAL_DEFAULT_LIMIT",
    "get_administracion_por_id",
    "get_administraciones",
    "get_administraciones_para_tabla",
    "buscar_administracion_por_nombre",
    "buscar_administracion_por_email",
    "buscar_administraciones_fuzzy",
    "create_administracion",
    "update_administracion",
    "delete_administracion",
    "get_comunidad_por_id",
    "get_comunidades",
    "get_comunidades_para_tabla",
    "buscar_comunidad_por_nombre",
    "buscar_comunidades_fuzzy",
    "create_comunidad",
    "update_comunidad",
    "delete_comunidad",
    "get_contactos",
    "get_contactos_para_tabla",
    "get_contactos_por_administracion_id",
    "get_contactos_por_comunidad_id",
    "get_administracion_ids_para_contacto",
    "get_comunidad_ids_para_contacto",
    "set_administracion_contacto",
    "set_comunidad_contacto",
    "set_contactos_para_administracion",
    "set_contactos_para_comunidad",
    "create_contacto",
    "update_contacto",
    "delete_contacto",
    "registrar_presupuesto",
    "get_historial_reciente",
    "actualizar_acceso",
    "actualizar_total",
    "eliminar_historial",
    "buscar_historial",
    "get_presupuesto_por_ruta",
    "get_presupuesto_detalle_por_ruta",
    "get_presupuestos_por_estado",
    "upsert_presupuesto",
    "upsert_presupuesto_finalizado",
    "get_partidas_de_presupuesto",
    "get_presupuestos_para_tabla",
    "actualizar_estado_presupuesto",
    "limpiar_presupuestos_huerfanos",
    "get_all_presupuestos_cache",
]
